# This workflow validates all pipeline WDL files using the 'womtool' tool.
name: WomtoolCheck

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  validate_wdl_job:
    runs-on: ubuntu-latest
    name: Validate all wdl using womtool
    steps:
      - uses: actions/checkout@v2
        with:
          repository: broadinstitute/smartseq2-single-nucleus-multisample
      - name: Run womtools
        run: |
          ./scripts/validate_wdls.sh